import re
import urllib2


class Parse(object):
	"""This is giant class which will handle the giant string, called source, generated by the urllib read function."""

	def __init__(self, data):
		self.data = data
		self.split(data)

	def split(self, data):
		self.sections = dict()
		equal = re.compile(r"^=+.*=+$")
		section = ""
		section_data = ""
		for line in data:
			result = equal.match(line)
			if result == None:
				section_data += line
				continue
			else:
				self.sections[section] = section_data
				section = result.group().strip('=')
				section_data = ""


data = urllib2.urlopen("http://en.wiktionary.org/w/index.php?action=raw&title=example")
example = Parse(data)
print example.sections["English"]
print example.sections["Etymology"]
